name: open_weather_api_client
description: A dart library for interfacing with the Open Weather API
version: 1.0.0
homepage: https://tanzilzubair.github.io
repository: https://github.com/tanzilzubair/open_weather_api_client

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  retry: ^3.1.0
  tuple: ^2.0.0
  http: ^0.13.3
  intl: ^0.17.0
  connectivity: ^3.0.3
  flutter_icmp_ping: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

